### ISSUE TITLE
Easy setting is not easy

### ISSUE THREAD

**Issue by MrNukealizer** [Starwaster/DeadlyReentry#10]
The default easy setting seems vastly harder than normal or hard. I think it's because the heat multiplier is 25 instead of 1.

**Comment by Starwaster** [comment]
Heat multiplier that low is only appropriate if the alternate heat model (in the beta) is enabled. In the current beta update, the 3 main difficulty settings are getting minor rewrites (and restored to pre-beta levels, which were primarily for testing the new heat model, which will have its own preset buttons)
