### ISSUE TITLE
Heat shield mass.

### ISSUE THREAD

**Issue by futrtrubl** [Starwaster/DeadlyReentry#11]
The base mass of the 2.5m heat shield is 0.06t which agrees roughly with the mass of the Huygens 2.7m heat shield at 79kg (though that included ablative mass).
However, the smaller 1.25m heat shield despite being smaller weighs 3x as much at 0.2t. Actually all the other heat shields have the same base structural mass of 0.2t.

**Comment by Draconomial** [comment]
That is weird

**Comment by Starwaster** [comment]
Adjusted heat shield masses.
