### ISSUE TITLE
Can't add parts to DR heatshields

### ISSUE THREAD

**Issue by hahawin** [Starwaster/DeadlyReentry#12]
When using the heatshields that come with v7.0 of DR I cant seem to attach anything underneath it. I tried both the 0.625m and the 1.25m shields, using decouplers and other parts. 

Steps to reproduce:
1. Create pod in VAB
2. (optional) place somthing underneath pod (fuel tank/science module,..)
3. Place heathsield.
4. Try to attach decoupler or other part to heathshield, it doesnt work.

**Comment by Starwaster** [comment]
Fixed
