### ISSUE TITLE
Poor performance with DR on RSS/RO install

### ISSUE THREAD

**Issue by Disoculated** [Starwaster/DeadlyReentry#27]
I have a performance problem in RSS/RO (CKAN install) that I have narrowed down to Deadly Reentry 7.3.1.

Getting significant time lag whenever a ship is loaded, and the logfile is spammed with the following message:
NullReferenceException: Object reference not set to an instance of an object
  at DeadlyReentry.ModuleHeatShield.FixedUpdate () [0x00000] in <filename unknown>:0

While this is happening, performance drops to less than 10fps, despite being below 10% GPU and CPU utilization (sort of like there's a pause or sleep in there).  

Machine is a 3.4ghz i7 with GTX 980ti on Windows 7 with 32GB of RAM (2.5GB used by KSP), and I get horrible time lag.  Every launch over a hundred parts gives a yellow clock and a 3X or more time reduction

At KSC and until I load a vessel, I get 60fps.

The only mods installed are FASA and required mods for RSS/RO via CKAN.

 Have tried multiple deletions and reinstallations of KSP RSS/RO, and still get this issue.  If there is anymore information that you'd like me to provide, just let me know.

  Thank you for the time you put into this mod!

[output_log.txt](https://github.com/Starwaster/DeadlyReentry/files/148788/output_log.txt)

**Comment by Starwaster** [comment]
That's coming from an improperly configured heat shield, probably from Realism Overhaul. I've considered suppressing the error which would probably stop the lag but that wouldn't change the fact that a heat shield is badly configured and then you would have a heat shield failing without an error. 

I can't look at your log as my PC is down so i suggest posting it in the RO forum or in IRC (espernet network, channel #RO)
