### ISSUE TITLE
too hard for the early game, regression or intentional?

### ISSUE THREAD

**Issue by fommil** [Starwaster/DeadlyReentry#29]
Hi, I was a big fan of this plugin in kerbal 0.9-ish and possibly 1.0. But I started playing Kerbal again with 1.1.3 and I found it makes it almost impossible to reenter in the early game. For example, with a Mk1 crew cabin and a Mk1 pod, with a heat shield, in a 100k ap it is not possible to orient the ship in any way such that it survives reentry.... even if it comes in as shallow as a 60k pe.

Is this an intentional regression?

**Comment by Starwaster** [comment]
It's that crew cabin. A 1.25m shield can't give enough coverage and the cabin lacks sufficient shielding for that kind of descent.

**Comment by fommil** [comment]
That makes it impossible to do the tourist contracts, so the career mode is no fun. Maybe a larger heatshield should be introduced earlier.

**Comment by Starwaster** [comment]
Just because a contract is offered doesn't mean it has to be accepted. Nor does it mean that there's an issue if doing the contract turns out to be 'impossible'. Sometimes you have to put contracts off for a better day.

**Comment by fommil** [comment]
I hadn't realised that stock kerbal added some risk around reentry. That's probably enough for me. I'll use DE2 if I am playing in sandbox and want more realism.
