### ISSUE TITLE
Kerbals explode on eva

### ISSUE THREAD

**Issue by DennisKerman** [Starwaster/DeadlyReentry#33]
Hi,
Unfortunately my Kerbals tend to randomly explode while on eva. If new Kerbal (eg from contract) is joining and going eva for the transfer he/she WILL explode for sure.
Other Kerbals somtimes burn... like if there was athmosphere and they were parts close to failing.
Using KAS/KIS and manipulating stuff there is a ranfom chance my Kerbals will go poof...

**Comment by Starwaster** [comment]
Download this file and copy it into your DeadlyReentry folder:
https://github.com/Starwaster/DeadlyReentry/raw/master/DeadlyReentry/DeadlyReentry-KerbalEVA.cfg

**Comment by DennisKerman** [comment]
Thanks for the quick response. It worked... but there seems to be an issue with my savegame cuz my ships burn too.. being far from any atmosphere.
But its all good. Made a new save, all fine now thanks alot!!
I love this mod.. it makes the ride down with my spaceplanes on low fuel really interesting ;-))
