### ISSUE TITLE
deadly reentry 7.6.0 is marked for KSP 1.2.99

### ISSUE THREAD

**Issue by glilienthal** [Starwaster/DeadlyReentry#37]
CKAN shows 7.6.0 for KSP 1.2, not 1.3

**Comment by glilienthal** [comment]
cf. pull request.

**Comment by Starwaster** [comment]
Request rejected. There are no official releases for KSP 1.3.0 and the latest official release _is_ for KSP 1.2.2

The changes you propose will only result in KSP 1.3.0 users downloading a version which will crash KSP 1.3.0

There is an _**unofficial**_ release and you may try it but read the notes in the download link carefully! It is unsupported in every way possible: https://github.com/Starwaster/DeadlyReentry/releases/tag/v7.6.0-KSP-1.3.0-beta (NOT MEANT TO SHOW UP ON CKAN!)
