### ISSUE TITLE
Unnamed Node.

### ISSUE THREAD

**Issue by 7ranceaddic7** [Starwaster/DeadlyReentry#43]
Getting this warning in KSP.log

[WRN 10:22:16.137] Config in file '/home/scott/Games/KSP_1.6.1/GameData/DeadlyReentry/DeadlyReentry-OPT.cfg' contains an unnamed node. Skipping.

Looks like the fault lies here:

https://github.com/Starwaster/DeadlyReentry/blob/3f2c95064bf472a26598adedca6b49e5263caca3/DeadlyReentry/DeadlyReentry-OPT.cfg#L97

remove 'name=' from inside PART node.

(I'll confirm/not this during the next start-up.)

**Comment by Starwaster** [comment]
Fixed
