### ISSUE TITLE
Deadly reentry hangs on the KSP 1.8.1 Main Menu

### ISSUE THREAD

**Issue by Myshiko** [Starwaster/DeadlyReentry#46]
Deadly reentry hangs right at the end of the load,  right before Main Menu. This happens only on KSP 1.8.1. The execution get stuck in WriteFile windows API call, the last entries in the KSP debug log are messages from the DRE.

This happens with installs with many part mods. Commenting out Debug.Log all over the code seems to prevent the hang.

Brutal patch to suppress all logging and private build for testing is provided in the link.
https://1drv.ms/u/s!Ao0C2PjqjY3ElkKNWbfaiO0SCVSh?e=Wifxd1

Permission granted to use it for any purpose, no warranty, an etc.

Probably deserves some cleanup and understanding what's wrong with Debug.Log.

**Comment by Starwaster** [comment]
No, it's not Debug.Log

That's a red herring.  As indicated in the forums, there's a fix in the works, it's had some testing that looks promising and I'll be trying to get a release out for it soon. As soon as my computer issues calm down.

**Comment by Starwaster** [comment]
Try this build:
https://www.dropbox.com/s/swzx88yinwf4hqv/DeadlyReentry.dll?dl=1

If it still hangs then submit logs

**Comment by Myshiko** [comment]
Looks to be not hanging any more (on a first glace). Will test some more, and let you know if I encounter obvious problems.
