### ISSUE TITLE
Reentry

### ISSUE THREAD

**Issue by DJDC13** [Starwaster/DeadlyReentry#48]
I have rss, ro with all dependencies. Whatever heat shield i try (deadly reentry shields or the realism overhaul shields) craft explodes on reentry. Even if i set my periapse to 80km from a 200 km x 200 km orbit as soon as I get to about 70 km altitude I will explode. The alblator is hardly touched at this point, maybe used about 100 units at the most. Alt + D + R does not open a config menu for me but the button on the toolbar opens the dialogue box with the heat slider, even putting this down to 10% has no better results. Speed is normal orbital speed around 7.8 km/s.

**Comment by Starwaster** [comment]
There is no hot keys to open the menu anymore. That's outdated information that somehow escaped deletion.

As for the reentry problem it sounds like something isn't configured properly. Please enclose links to your log file and ModuleManager.ConfigCache 

The MM cache is in your GameData folder and your log can be the ksp.log file in the KSP folder.

**Comment by DJDC13** [comment]
ok my KSP log file is 26.2Mb so cant upload it on here. I have the module manager log file but not the cache file (I use to see the cache file not sure why it is not there now)

**Comment by Starwaster** [comment]
Then zip it up. And/Or put it on dropbox and paste the link here

If you have no MM cache file then there are errors in one of your config files which will prevent the cache from being written

**Comment by DJDC13** [comment]
https://www.dropbox.com/sh/c72f2hingtjwhxt/AAAOfpHUNn4jNpGggBtpodJLa?dl=0

thanks here is the link to the dropbox folder

**Comment by Starwaster** [comment]
13 errors related to GameData/Cormorant Aeronology/Patches/RO/Mk3_shuttle.cfg

Delete that mod (temporarily at least) then run the game. ModuleManager.ConfigCache should be generated then.

Get that file and post a link to it please.

**Comment by DJDC13** [comment]
I know it has been a while but the world is a bit crazy right now but if anyone is still looking at these here are my logs after deleting the cormorant aeronology. Although I think the error for that mod was popping up due to me editing the part.cfg files for the space shuttle to make it work with realism scale as the mods RSS patch did not work.,

https://www.dropbox.com/sh/c72f2hingtjwhxt/AAAOfpHUNn4jNpGggBtpodJLa?dl=0

**Comment by Starwaster** [comment]
Sorry to take so long, I took a look at your logs and cache and I don't see anything there that's a problem.

Maybe this is a design issue in the craft? I was assuming simple things like capsules but there's a few design issues that can trip you up. For instance 

- trying to attach cylindrical parts to the heat shield. The shield needs to be wider than the payload. If the sides of the cylinder are exposed to the shockwave in even the slightest degree it will probably burn up. Things like resource containers or the Science Jr part. (is that even available in RO? Not sure)
- Craft with irregular shapes (landing legs, radially attached engines, etc) - the shield needs to be wide enough to keep the shockwave away from the payload/craft unless you have a backshell to protect it.

**Comment by kellpossible** [comment]
perhaps this is related to #51 ? which way does your craft face during descent, prograde or retrograde?
