### ISSUE TITLE
Heashield facing prograde is innefective

### ISSUE THREAD

**Issue by kellpossible** [Starwaster/DeadlyReentry#51]
Reentry from orbit of 200km. KSP 1.10.1 [configured with RP-1](https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.10.1)

With heatshield facing prograde:
![20210611205208_1](https://user-images.githubusercontent.com/4527338/121660087-0dab6000-caf7-11eb-85e8-5e46d1a4ce08.jpg)

Just before the part explodes:
![20210611205229_1](https://user-images.githubusercontent.com/4527338/121660315-45b2a300-caf7-11eb-9d41-0d1a9e32b8da.jpg)

With heatshield facing retrograde:
![20210611204512_1](https://user-images.githubusercontent.com/4527338/121660059-0421f800-caf7-11eb-9978-b23740281099.jpg)

Zip containing the prograde (*Heatshield Bug.craft*) and retrograde (*Heatshield Bug Fixed.craft*) crafts.
[Crafts.zip](https://github.com/Starwaster/DeadlyReentry/files/6637130/Crafts.zip)

I'm assuming this is a problem with deadly reentry, but perhaps it's also a bug in stock or with FAR (I don't know how it interacts with deadly reentry), I didn't check yet.

**Comment by Starwaster** [comment]
Deadly Reentry has zero effect on how parts receive heating. It only affects what happens to them after they receive that heat (and when they overheat). The problem you're having is how parts are and are not occluding each other. Look at all the other parts in there, not just one or two of them. Where are those parts coming from? Are any of them procedural? Replace them with only stock parts (resized for RO is fine) and non-procedural. 

Also try without FAR and if you have Real Heat installed, try removing that and see if the problem persists.

**Comment by kellpossible** [comment]
Thanks yeah it looks like removing FAR (and B9 procedural wings) solved it. Probably it's a problem with FAR.
