### ISSUE TITLE
part temperature is confused with heatsink temperature

### ISSUE THREAD

**Issue by byt3c** [Starwaster/DeadlyReentry#60]
There is problem with radiators that have weridly temperature of heatsink way lower than part temperature.

There is problem with cooling on spacecraft especially with atmospheric vehicles heatsink temperature seems to be somewhat random while part temperature is rising with heat sources on the vehicle...

![screen](https://user-images.githubusercontent.com/38114978/181779970-7e0bd4e8-c188-418c-84ae-6af222c64810.png)

There is also issue with skin max temp lower than max radiator temperature.

**Comment by byt3c** [comment]
![screen](https://user-images.githubusercontent.com/38114978/181778375-4cae0c4b-0d89-434f-809c-fdbe6e76ccee.png)
It would be good to display on debug section of part temperature of selected part (not only for radiators)

**Comment by Starwaster** [comment]
The radiator section there has nothing to do with Deadly Reentry. Heatsink has nothing to do with it either. That looks like Nertea's NF radiator mod.  You're confusing the sections of two different mods with each other. Also it sounds like you're confusing what the heatsink section is actually saying but that's something you should direct at Nertea. Post any questions in the forum for his mod.

Regarding the DR debug section, that is not showing the part's actual max temps and none of them shows the skin max temp being lower than the part max temp. What they are showing is the temperatures at which the part starts to weaken or be damaged, which is a lower temperature than stock KSP's max temp, which is an absolute limit at which the part is destroyed. (explodes or vaporizes)

**Comment by byt3c** [comment]
Thank you for exhaustive explanation. The point is, that radiators are being heated up quite unpredictably (regardles of bugs and mods) and it would be good for deadly reentry to set operational temperature for radiators somewhat higher than their designed maximums.

Can you give me a link to his repo / project ? i got this package from ksp interstellar.

**Comment by Starwaster** [comment]
Then it's probably KSPI you want to go to instead. I just assumed it was Nertea's Near Future mods.

Regarding changing the operational temps, I'm not averse to adding in some patches for other mods; DR is full of them. But I'd need more information like part names and thermal parameters for guidance. I've never used KSPI so I have no information on them.

**Comment by Starwaster** [comment]
Ok so I went and looked at KSPI repo here on GitHub and it looks like at one point he was patching it to outright exempt his radiator parts from Deadly Reentry's handling. However, he later changed that to delete the ModuleAeroReentry PartModule, which will not work (not by itself). DR will add that module to every part that is missing it (except flags)

So his current patch won't work. (pinging him below)

@sswelm all you need is: (in addition to deleting any existing MAR modules)
```
   	MODULE
   	{
   	   	name = ModuleAeroReentry
   	   	leaveTemp = True
   	}
```
skinHeatConductivity and skinThicknessFactor don't do anything anymore; the entire skin system became part of stock KSP.

**Comment by byt3c** [comment]
Thank you for this info. Though I'm developer / architect myself, i never dwelled into modding KSP. And it seems pretty simple. But i would need to setup whole environment and learn to use studio code ;) not bad challenge ;)
