### ISSUE TITLE
Hard reentries in certain configurations crash the game [RO]

### ISSUE THREAD

**Issue by Noiredd** [Starwaster/DeadlyReentry#61]
In RO/RSS, a very fast reentry (~11km/s) on a LEO-rated heatshield should result in the vehicle spectacularly exploding. However, in certain vehicle configurations, hard reentry _explodes_ the entire game, crashing it on the spot (Unity Crash Handler pops up for a split second). After a few days of tracking the source of my crashes, I found DR to be the culprit - without it, the vehicle undergoes a typical fiery RUD.

This started to happen when I was experimenting with aerocapture probes in a heat shell made of a heat shield and a procedural fairing (screenshot attached). Interestingly, I was unable to reproduce it on a "typical" build such as a Mk2 Pod + heat shield. Reproducing it might therefore be a bit inconvenient, as one has to build something like this (instructions below, I promise I've made it as bare-bones as possible).

Environment:
* KSP v1.12.5 (Steam)
* RO v17.3.0.0 (CKAN install with all requirements)
* RSS v.20.1.0.0
* ProceduralFairings v6.4.1.0 and ProceduralParts v2.5.4.0 (required to build the vehicle)
* **DR v7.9.0**

To build the vehicle (screenshot below for a rough reference):
* start with an `Early Controllable Core`
* optionally, add a `Procedural Tank` (or an Oscar) filled with some LeadBallast below it
* place an `FB - FB - Procedural Hollow Payload Adapter Ring` below (this will make the heat shell)
* place a pair of `Procedural Fairing - Conic (White)` to close the shell (disable "Use Preset" and reduce "Nose-Height Ratio" to 1.00)
* complete the heat shell with a `LEO Heat Shield` of a matching size (it shouldn't matter, I observed the same results for 2m, 2.5m, 3m etc) _// if one was to use a lunar-rated shield instead, everything would go fine, i.e. a normal reentry_
* additionally, to make testing easier, I add a small "service module" below: some decoupler, a high-pressure tank, and some RCS nozzles.

To reproduce the crash, launch this vehicle, and use the cheat menu to set orbit to:
* semi-major axis: 200 000 000
* eccentricity: 0.9678
* inclination: 60
* MNA: 6.275
* (remember to _override safety check_).

This should result in a very hard reentry (11km/s at 69km perigee). Orient the craft correctly, decouple the service section to expose the heat shield, and at around 70-80km your game should crash. It crashes so violently in fact, that the log isn't even being flushed to disk (and so it doesn't contain anything around the time of the crash).

I _suspect_ this is due to heating becoming so intense that the equations throw a NaN or an Inf somewhere (due to the finite and rather coarse time step of the simulation). To support this hypothesis: I experimented with one particular vehicle, trying higher and higher orbits, and found that the crashes started to occur after a certain point (e.g. sma=13 500 000, ecc=0.524 would be a normal reentry, but at sma=13 700 000, ecc=0.53095 the game would crash).

![DRcrashvehicle](https://github.com/Starwaster/DeadlyReentry/assets/17203018/230af2bd-1fb2-40c4-9089-3a16f2764027)
_This is roughly how the test vehicle should look like, one half of the fairing is removed to show the interior._

**Comment by Starwaster** [comment]
Be sure to check the player.log file in %localappdata%low\Squad\Kerbal Space Program

There is also a Crashes folder in there as well. Reproduce the problem then grab the player.log file and the relevant crash folder from inside Crashes and add those files to this issue. 

(deleted part about output_log.txt)

**Comment by Starwaster** [comment]
I am currently unable to reproduce this issue. I suspect interaction with another mod. My first suspect would be FAR followed by Procedural Fairing since these are not mods I usually run with. However, installing those did not help me reproduce the issue.

I likewise do not use RSS or RO, but I do use a scaled up 10x Kerbol System so reproducing a reentry of the parameters you specify is trivial; I do it all the time and have never experienced the issue you describe. (this also means that your suspicions as to cause are extremely unlikely. 'intense heating' doesn't cause math errors)

Your description as to timing of the crash seem to indicate that it is happening either when the shield runs out of ablator or when the part is being destroyed.

Absent any logs of the event, I don't see this being resolved any time soon.
