### ISSUE TITLE
not deadly enough?

### ISSUE THREAD

**Issue by fommil** [Starwaster/DeadlyReentry#7]
I love the added realism of having the think about re-entry. Thank you for continuing this adon.

I recently tried something out: I had a kerbal-recovery mission from a science station in Mun orbit: three kerbals returning in a Mk1-2 pod. I used an absolutely tiny amount of deltav to get out of Mun orbit and then burnt retrograde to reduce my Pe to 40k (with an Ap stretching almost back to the Mun).

I was pretty amazed that the heatshield held up and only about 5% of the ablative was used during the manoeuvre. The pod slowed to parachute speeds/altitude and I landed safely.

Is this expected behaviour?

I'd really like to be able to predict in advance how much shielding I need for a given mass/velocity combination. Would be a nice addition to my web calculators and would make the design stage more fun (for me, at least): http://fommil.github.io/kerbal/

(ironically, I've worked on such calculations for realz for non-Earth re-entry, so you can see why I'd want to have this as a consideration in KSP :-))

btw, I'm using FAR.

**Comment by Starwaster** [comment]
The next version will have an alternate heating model to make things deadlier. There's a beta of it in the release section though the settings on Easy / Default make it a little too deadly. (heat multiplier of 20 instead of 1)

**Comment by fommil** [comment]
Cool! Any docs on how it works for design calculations?

**Comment by Starwaster** [comment]
The version you were asking about used calculations from a document at this FAA site: https://www.faa.gov/other_visit/aviation_industry/designees_delegations/designee_types/ame/media/Section%20III.4.1.7%20Returning%20from%20Space.pdf

**Comment by fommil** [comment]
what about the latest version, has much changed?
