### ISSUE TITLE
When cargo bay or fairing burns up cargo not exposed (may involve FAR)

### ISSUE THREAD

**Issue by MrNukealizer** [Starwaster/DeadlyReentry#8]
I was doing a reentry test with FAR, Procedural Fairings and Deadly Reentry installed when the following happened. The craft was a basic rocket with everything except the engine inside a procedural fairing and the engine on the bottom of the ring.

The craft came in fast enough that half of the fairing and the engine burned up. A few seconds later the other half of the fairing burned up. By that time the cargo should have already been damaged by heat or aerodynamics but was still intact. Even after both halves of the fairing had burned up the cargo and ring were not heating up at all. Even going straight backwards the ring was unaffected. At that point I noticed I wasn't losing any speed and FAR was said the terminal velocity was infinite. To be sure I did another orbit passing below 23k meters and my orbit was unchanged, so the craft obviously no longer had any drag.

I tested the same craft again as well as three other designs using cargo bays also, and every time the parts inside the fairing/bay as well as the fairing ring were dragless and immune to heat after the rest of the crafts were destroyed.

Parts tested: 
Mk3 Cargo Bay CRG-50 (stock)
HL Cargo Bay 4m (B9 Aerospace)
Procedural Fairings

**Comment by Starwaster** [comment]
Going to have to say this is a FAR issue. When FAR is installed, we trust it when it says a part is shielded. No other checks are made after that.
